{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "codimd.fullname" . }}
  {{ if .Values.ingress.annotation}}
  annotations:
    {{ toYaml .Values.ingress.annotation | nindent 4 }}
  {{ end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - backend:
              serviceName: {{ template "codimd.fullname" . }}
              servicePort: 80
  {{ if .Values.ingress.tlsSecret }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.tlsSecret }}
  {{ end }}
  {{ end }}